let playerArray = [
    {
      playerInfo: {
        name: "broky",
        realName: "Helvijs Saukants",
        nationality: " Latvia",
        birthDate: "2001-02-14",
        team: "FaZe Clan",
        role: "AWPer",
        approxWinnings: "$171,883",
        age: 20,
      },
      statistics: {
        rating: 1.08,
        adr: 72.3,
        kpr: 0.68,
        dpr: 0.62,
        impact: 0.99,
        totalKills: 9743,
        totalDeaths: 8770,
        mapsPlayed: 535,
        roundsplayed: 14230,
        hsPercentage: 40.2,
        kdRatio: 1.11,
      },
      gear: {
        mouse: "Logitech G PRO X SUPERLIGHT",
        keyboard: "SteelSeries Apex Pro",
        headset: "SteelSeries Arctis Pro",
        mousepad: "SteelSeries QcK+",
        monitor: "ZOWIE XL2546",
      },
      settings: {
        dpi: 400,
        sensitivity: 1.9,
        zoomSensitivity: 1,
        resolution: "1280x960",
        scalingMode: "Stretched",
        crosshair:
          "cl_crosshairalpha 255; cl_crosshaircolor 4; cl_crosshairdot 1; cl_crosshairgap -1; cl_crosshairsize 1; cl_crosshairstyle 5; cl_crosshairthickness 0; cl_crosshair_sniper_width 1; cl_crosshair_drawoutline 0",
      },
      career: {
        trophies: [
          "IEM New York 2020 Europe",
          "BLAST Pro Series Copenhagen 2019",
        ],
      },
      playerId: "18053",
      playerName: "broky",
      hltvUrl: "https://www.hltv.org/player/18053/broky",
      liquipediaUrl: "https://liquipedia.net/counterstrike/broky",
      highlights: [
        {
          name: "broky vs. Spirit",
          url: "https://hltv.org/news/32042/video-broky-vs-spirit",
        },
        {
          name: "broky vs. G2",
          url: "https://hltv.org/news/31933/video-broky-vs-g2",
        },
      ],
    },
    {
      playerInfo: {
        name: "Twistzz",
        realName: "Russel David Van Dulken",
        nationality: " Canada",
        birthDate: "1999-11-14",
        team: "FaZe Clan",
        role: "Rifler",
        approxWinnings: "$886,022",
        age: 22,
      },
      statistics: {
        rating: 1.11,
        adr: 77,
        kpr: 0.74,
        dpr: 0.62,
        impact: 1.08,
        totalKills: 23436,
        totalDeaths: 19868,
        mapsPlayed: 1215,
        roundsplayed: 31804,
        hsPercentage: 62.3,
        kdRatio: 1.18,
      },
      gear: {
        mouse: "VAXEE OUTSET AX",
        keyboard: "SteelSeries Apex Pro",
        headset: "SteelSeries Arctis Pro",
        mousepad: "SteelSeries QcK+",
        monitor: "Alienware AW2518HF",
      },
      settings: {
        dpi: 400,
        sensitivity: 2,
        zoomSensitivity: 1,
        resolution: "1280x960",
        scalingMode: "Stretched",
        crosshair:
          "cl_crosshairalpha 255; cl_crosshaircolor 5; cl_crosshaircolor_r 255; cl_crosshaircolor_g 0; cl_crosshaircolor_b 255; cl_crosshairdot 0; cl_crosshairgap -4.4; cl_crosshairsize 1.1; cl_crosshairstyle 4; cl_crosshairthickness 0.8; cl_crosshair_drawoutline 0",
      },
      career: {
        trophies: [
          "ESL Pro League Season 11 North America",
          "IEM Chicago 2019",
          "BLAST Pro Series Los Angeles 2019",
          "ESL One Cologne 2019",
          "ESL Pro League Season 9 Finals",
          "DreamHack Masters Dallas 2019",
          "IEM Sydney 2019",
          "iBUYPOWER Masters 2019",
          "SuperNova CS:GO Malta",
          "cs_summit 2",
        ],
      },
      playerId: "10394",
      playerName: "twistzz",
      hltvUrl: "https://www.hltv.org/player/10394/twistzz",
      liquipediaUrl: "https://liquipedia.net/counterstrike/twistzz",
      highlights: [
        {
          name: "Twistzz vs. Gambit",
          url: "https://hltv.org/news/32072/video-twistzz-vs-gambit",
        },
        {
          name: "Twistzz vs. Vitality",
          url: "https://hltv.org/news/32049/video-twistzz-vs-vitality",
        },
        {
          name: "Twistzz vs. BIG",
          url: "https://hltv.org/news/31962/video-twistzz-vs-big",
        },
        {
          name: "Twistzz vs. Vitality",
          url: "https://hltv.org/news/31365/video-twistzz-vs-vitality",
        },
        {
          name: "Twistzz vs. 100 Thieves",
          url: "https://hltv.org/news/30446/video-twistzz-vs-100-thieves",
        },
        {
          name: "Twistzz vs. Evil Geniuses",
          url: "https://hltv.org/news/30325/video-twistzz-vs-evil-geniuses",
        },
        {
          name: "Twistzz - The Canadian star",
          url: "https://hltv.org/news/27602/video-twistzz-the-canadian-star",
        },
        {
          name: "Twistzz vs. Vitality",
          url: "https://hltv.org/news/27289/video-twistzz-vs-vitality",
        },
        {
          name: "Twistzz vs. MIBR",
          url: "https://hltv.org/news/27156/video-twistzz-vs-mibr",
        },
        {
          name: "Twistzz - MVP of IEM Sydney 2019",
          url: "https://hltv.org/news/26739/video-twistzz-mvp-of-iem-sydney-2019",
        },
        {
          name: "Twistzz vs. fnatic",
          url: "https://hltv.org/news/25323/video-twistzz-vs-fnatic",
        },
        {
          name: "Twistzz – MVP of ESL One New York",
          url: "https://hltv.org/news/25108/video-twistzz-mvp-of-esl-one-new-york",
        },
      ],
    },
    {
      playerInfo: {
        name: "rain",
        realName: "Håvard Nygaard",
        nationality: " Norway",
        birthDate: "1994-08-27",
        team: "FaZe Clan",
        role: "Rifler (entry fragger)",
        approxWinnings: "$793,836",
        age: 27,
      },
      statistics: {
        rating: 1.03,
        adr: 80.1,
        kpr: 0.71,
        dpr: 0.69,
        impact: 1.16,
        totalKills: 27441,
        totalDeaths: 26570,
        mapsPlayed: 1455,
        roundsplayed: 38453,
        hsPercentage: 56.3,
        kdRatio: 1.03,
      },
      gear: {
        mouse: "Dream Machines DM2 Comfy",
        keyboard: "SteelSeries Apex 7 TKL",
        headset: "SteelSeries  Arctis Pro",
        mousepad: "SteelSeries  QcK Heavy",
        monitor: "ZOWIE  XL2546",
      },
      settings: {
        dpi: 400,
        sensitivity: 1.65,
        zoomSensitivity: 1,
        resolution: "1280x960",
        scalingMode: "Stretched",
        crosshair:
          "cl_crosshairalpha 200; cl_crosshaircolor 1; cl_crosshaircolor_r 250; cl_crosshaircolor_g 250; cl_crosshaircolor_b 50; cl_crosshairdot 0; cl_crosshairgap -5; cl_crosshairsize 1.5; cl_crosshairstyle 4; cl_crosshairthickness 1; cl_crosshair_outlinethickness 0; cl_crosshair_drawoutline 0",
      },
      career: {
        trophies: [
          "IEM New York 2020 Europe",
          "BLAST Pro Series Copenhagen 2019",
          "BLAST Pro Series Miami 2019",
          "ELEAGUE CS:GO Invitational 2019",
          "EPICENTER 2018",
          "ESL One Belo Horizonte 2018",
          "IEM Sydney 2018",
          "ECS Season 4 Finals",
          "ESL One New York 2017",
          "ELEAGUE CS:GO Premier 2017",
          "SL i-League StarSeries Season 3 Finals",
        ],
      },
      playerId: "8183",
      playerName: "rain",
      hltvUrl: "https://www.hltv.org/player/8183/rain",
      liquipediaUrl: "https://liquipedia.net/counterstrike/rain",
      highlights: [
        {
          name: "rain vs. Liquid",
          url: "https://hltv.org/news/28972/video-rain-vs-liquid",
        },
        {
          name: "rain vs. Evil Geniuses",
          url: "https://hltv.org/news/28342/video-rain-vs-evil-geniuses",
        },
        {
          name: "rain vs. Cloud9",
          url: "https://hltv.org/news/27363/video-rain-vs-cloud9",
        },
        {
          name: "rain vs. B.O.O.T-d[S]",
          url: "https://hltv.org/news/24148/video-rain-vs-boot-ds",
        },
        {
          name: "rain vs. Liquid",
          url: "https://hltv.org/news/23997/video-rain-vs-liquid",
        },
        {
          name: "rain - MVP of ECS Season 4 Finals",
          url: "https://hltv.org/news/22317/video-rain-mvp-of-ecs-season-4-finals",
        },
        {
          name: "rain - MVP of ELEAGUE Premier",
          url: "https://hltv.org/news/21835/video-rain-mvp-of-eleague-premier",
        },
        {
          name: "rain vs. OpTic",
          url: "https://hltv.org/news/19381/video-rain-vs-optic",
        },
        {
          name: "rain vs. Luminosity",
          url: "https://hltv.org/news/16899/video-rain-vs-luminosity",
        },
        {
          name: "rain vs. EnVyUs",
          url: "https://hltv.org/news/16286/video-rain-vs-envyus",
        },
        {
          name: "rain vs. Natus Vincere",
          url: "https://hltv.org/news/15889/video-rain-vs-natus-vincere",
        },
        {
          name: "rain vs. PENTA",
          url: "https://hltv.org/news/15555/video-rain-vs-penta",
        },
        {
          name: "rain vs. Virtus.pro",
          url: "https://hltv.org/news/15496/video-rain-vs-virtuspro",
        },
        {
          name: "rain vs. INSHOCK",
          url: "https://hltv.org/news/14648/video-rain-vs-inshock",
        },
        {
          name: "rain vs. EnVyUs",
          url: "https://hltv.org/news/14444/video-rain-vs-envyus",
        },
        {
          name: "rain vs. TSM",
          url: "https://hltv.org/news/14302/video-rain-vs-tsm",
        },
      ],
    },
    {
      playerInfo: {
        name: "olofmeister",
        realName: "Olof Kajbjer Gustafsson",
        nationality: " Sweden",
        birthDate: "1992-01-31",
        team: "FaZe Clan",
        role: "Rifler (support)Rifler (lurker)",
        approxWinnings: "$901,819",
        age: 29,
      },
      statistics: {
        rating: 1.06,
        adr: 73.5,
        kpr: 0.72,
        dpr: 0.65,
        impact: 1.03,
        totalKills: 28030,
        totalDeaths: 25243,
        mapsPlayed: 1493,
        roundsplayed: 39018,
        hsPercentage: 46.3,
        kdRatio: 1.11,
      },
      gear: {
        mouse: "ZOWIE EC2-B",
        keyboard: "SteelSeries Apex Pro",
        headset: "SteelSeries Arctis Pro",
        mousepad: "SteelSeries QcK Heavy",
        monitor: "ZOWIE XL2540",
      },
      settings: {
        dpi: 400,
        sensitivity: 1.7,
        zoomSensitivity: 1.2,
        resolution: "1024 x768",
        scalingMode: "Black Bars",
        crosshair:
          "cl_crosshairalpha 5000; cl_crosshaircolor 1; cl_crosshairdot 0; cl_crosshairgap -2.5; cl_crosshairsize 4; cl_crosshairstyle 4; cl_crosshairthickness 0.7; cl_crosshair_sniper_width 1; cl_crosshair_drawoutline 0",
      },
      career: {
        trophies: [
          "BLAST Pro Series Copenhagen 2019",
          "BLAST Pro Series Miami 2019",
          "ELEAGUE CS:GO Invitational 2019",
          "EPICENTER 2018",
          "ECS Season 4 Finals",
          "ESL One New York 2017",
          "ELEAGUE CS:GO Premier 2017",
          "IEM Katowice 2016",
          "ESL Barcelona CS:GO Invitational presented by Mobile World Congress",
          "SL i-League StarSeries XIV Finals",
          "ESL ESEA Pro League Season 2 Finals",
          "Fragbite Masters Season 5 Finals",
          "FACEIT League 2015 Stage 3 Finals at DH Winter 2015",
          "ESL One Cologne 2015",
          "ESL ESEA Pro League Season 1 Finals",
          "DreamHack Open Summer 2015",
          "Gfinity 2015 Spring Masters 2",
          "DreamHack Open Tours 2015",
          "ESL One Katowice 2015",
          "Inferno Online Pantamera Challenge",
          "ESEA Invite Season 17 Global Finals",
          "Fragbite Masters Season 3 Finals",
          "ESWC 2014",
          "FACEIT League Season 2 Finals",
          "SLTV StarSeries X Finals",
        ],
      },
      playerId: "885",
      playerName: "olofmeister",
      hltvUrl: "https://www.hltv.org/player/885/olofmeister",
      liquipediaUrl: "https://liquipedia.net/counterstrike/olofmeister",
      highlights: [
        {
          name: "olofmeister vs. Complexity",
          url: "https://hltv.org/news/32017/video-olofmeister-vs-complexity",
        },
        {
          name: "olofmeister vs. Natus Vincere",
          url: "https://hltv.org/news/18334/video-olofmeister-vs-natus-vincere",
        },
        {
          name: "olofmeister vs. G2",
          url: "https://hltv.org/news/18146/video-olofmeister-vs-g2",
        },
        {
          name: "olofmeister vs. TSM",
          url: "https://hltv.org/news/18063/video-olofmeister-vs-tsm",
        },
        {
          name: "olofmeister vs. dignitas",
          url: "https://hltv.org/news/17131/video-olofmeister-vs-dignitas",
        },
        {
          name: "olofmeister and fnx",
          url: "https://hltv.org/news/16817/video-olofmeister-and-fnx",
        },
        {
          name: "olofmeister vs. EnVyUs",
          url: "https://hltv.org/news/16035/video-olofmeister-vs-envyus",
        },
        {
          name: "olofmeister vs. Virtus.pro",
          url: "https://hltv.org/news/14782/video-olofmeister-vs-virtuspro",
        },
        {
          name: "olofmeister vs. TSM",
          url: "https://hltv.org/news/14528/video-olofmeister-vs-tsm",
        },
        {
          name: "olofmeister vs. Na`Vi",
          url: "https://hltv.org/news/14454/video-olofmeister-vs-navi",
        },
      ],
    },
    {
      playerInfo: {
        name: "karrigan",
        realName: "Finn Andersen",
        nationality: " Denmark Germany",
        birthDate: "1990-04-14",
        team: "FaZe Clan",
        role: "In-game leaderRifler (entry fragger)",
        approxWinnings: "$1,029,089",
        age: 31,
      },
      statistics: {
        rating: 0.92,
        adr: 68.8,
        kpr: 0.63,
        dpr: 0.69,
        impact: 0.91,
        totalKills: 30386,
        totalDeaths: 33472,
        mapsPlayed: 1851,
        roundsplayed: 48408,
        hsPercentage: 42.6,
        kdRatio: 0.91,
      },
      gear: {
        mouse: "SteelSeries Rival 3 Wireless",
        keyboard: "SteelSeries Apex Pro",
        headset: "SteelSeries Arctis Pro",
        mousepad: "SteelSeries QcK",
        monitor: "ZOWIE XL2546",
      },
      settings: {
        dpi: 400,
        sensitivity: 1.4,
        zoomSensitivity: 1,
        resolution: "1600x1024",
        scalingMode: "Stretched",
        crosshair:
          "cl_crosshairalpha 255; cl_crosshaircolor 1; cl_crosshairdot 0; cl_crosshairgap -2; cl_crosshairsize 3; cl_crosshairstyle 4; cl_crosshairthickness 0; cl_crosshair_outlinethickness 0; cl_crosshair_drawoutline 0",
      },
      career: {
        trophies: [
          "ICE Challenge 2020",
          "cs_summit 5",
          "ESL Pro League Season 10 Finals",
          "CS:GO Asia Championships 2019",
          "EPICENTER 2018",
          "ESL One Belo Horizonte 2018",
          "IEM Sydney 2018",
          "ECS Season 4 Finals",
          "ESL One New York 2017",
          "ELEAGUE CS:GO Premier 2017",
          "SL i-League StarSeries Season 3 Finals",
          "PGL Season 1 Finals",
          "FACEIT League 2015 Stage 2 Finals at DreamHack Valencia",
          "Fragbite Masters Season 4 Finals",
          "FACEIT League 2015 Stage 1 Finals",
          "CCS Kick-off Season Finals",
        ],
      },
      playerId: "429",
      playerName: "karrigan",
      hltvUrl: "https://www.hltv.org/player/429/karrigan",
      liquipediaUrl: "https://liquipedia.net/counterstrike/karrigan",
      highlights: [
        {
          name: "karrigan vs. dignitas",
          url: "https://hltv.org/news/18236/video-karrigan-vs-dignitas",
        },
        {
          name: "karrigan vs. fnatic",
          url: "https://hltv.org/news/17468/video-karrigan-vs-fnatic",
        },
        {
          name: "karrigan vs. Luminosity",
          url: "https://hltv.org/news/16521/video-karrigan-vs-luminosity",
        },
        {
          name: "karrigan vs. Cloud9",
          url: "https://hltv.org/news/16458/video-karrigan-vs-cloud9",
        },
        {
          name: "karrigan vs. NiP",
          url: "https://hltv.org/news/16267/video-karrigan-vs-nip",
        },
        {
          name: "karrigan vs. EnVyUs",
          url: "https://hltv.org/news/15992/video-karrigan-vs-envyus",
        },
        {
          name: "karrigan vs. fnatic",
          url: "https://hltv.org/news/15872/video-karrigan-vs-fnatic",
        },
        {
          name: "karrigan vs. NiP",
          url: "https://hltv.org/news/14836/video-karrigan-vs-nip",
        },
        {
          name: "karrigan vs. Cloud9",
          url: "https://hltv.org/news/13778/video-karrigan-vs-cloud9",
        },
      ],
    },
    {
      playerInfo: {
        name: "Grim",
        realName: "Michael Wince",
        nationality: " United States",
        birthDate: "2000-11-22",
        team: "Team Liquid",
        role: "Rifler",
        approxWinnings: "$117,210",
        age: 21,
      },
      statistics: {
        rating: 1.12,
        adr: 79,
        kpr: 0.73,
        dpr: 0.68,
        impact: 1.13,
        totalKills: 14225,
        totalDeaths: 13354,
        mapsPlayed: 744,
        roundsplayed: 19546,
        hsPercentage: 48.1,
        kdRatio: 1.07,
      },
      gear: {
        mouse: "Logitech G PRO X SUPERLIGHT",
        keyboard: "HyperX Alloy Origins",
        headset: "HyperX Cloud Orbit",
        mousepad: "X-raypad Aqua Control",
        monitor: "ZOWIE XL2546",
      },
      settings: {
        dpi: 400,
        sensitivity: 1.55,
        zoomSensitivity: 1,
        resolution: "1024x768",
        scalingMode: "Black Bars",
        crosshair:
          "cl_crosshairalpha 200; cl_crosshaircolor 2; cl_crosshaircolor_r 1; cl_crosshaircolor_g 0; cl_crosshaircolor_b 255; cl_crosshairdot 0; cl_crosshairgap -3; cl_crosshairsize 3; cl_crosshairstyle 4; cl_crosshairthickness 1; cl_crosshair_outlinethickness 0; cl_crosshair_drawoutline 0",
      },
      career: { trophies: [] },
      playerId: "13578",
      playerName: "grim",
      hltvUrl: "https://www.hltv.org/player/13578/grim",
      liquipediaUrl: "https://liquipedia.net/counterstrike/grim",
      highlights: [
        {
          name: "Grim vs. Mythic",
          url: "https://hltv.org/news/30425/video-grim-vs-mythic",
        },
        {
          name: "Grim vs. 100 Thieves",
          url: "https://hltv.org/news/30348/video-grim-vs-100-thieves",
        },
      ],
    },
    {
      playerInfo: {
        name: "Stewie2K",
        realName: 'Jacky "Jake" Yip',
        nationality: " United States",
        birthDate: "1998-01-07",
        team: "Team Liquid",
        role: "In-game leaderRifler (entry fragger)",
        approxWinnings: "$1,140,190",
        age: 23,
      },
      statistics: {
        rating: 1.02,
        adr: 78,
        kpr: 0.7,
        dpr: 0.68,
        impact: 1.17,
        totalKills: 25617,
        totalDeaths: 25033,
        mapsPlayed: 1400,
        roundsplayed: 36561,
        hsPercentage: 49.5,
        kdRatio: 1.02,
      },
      gear: {
        mouse: "Glorious Model O",
        keyboard: "HyperX Alloy FPS Pro",
        headset: "HyperX Cloud II",
        mousepad: "SteelSeries QcK+",
        monitor: "Alienware AW2521H",
      },
      settings: {
        dpi: 400,
        sensitivity: 1.8,
        zoomSensitivity: 1.2,
        resolution: "1024x768",
        scalingMode: "Black Bars",
        crosshair:
          "cl_crosshairalpha 200; cl_crosshaircolor 1; cl_crosshaircolor_r 200; cl_crosshaircolor_g 50; cl_crosshaircolor_b 80; cl_crosshairdot 0; cl_crosshairgap 0; cl_crosshairsize 2; cl_crosshairstyle 4; cl_crosshairthickness 1; cl_crosshair_outlinethickness 1; cl_crosshair_drawoutline 0",
      },
      career: {
        trophies: [
          "ESL Pro League Season 11 North America",
          "IEM Chicago 2019",
          "BLAST Pro Series Los Angeles 2019",
          "ESL One Cologne 2019",
          "ESL Pro League Season 9 Finals",
          "DreamHack Masters Dallas 2019",
          "IEM Sydney 2019",
          "iBUYPOWER Masters 2019",
          "ZOTAC Cup Masters 2018 Grand Finals",
          "ELEAGUE Major 2018",
          "iBUYPOWER Masters 2017",
          "DreamHack Open Denver 2017",
          "ESL Pro League Season 4 Finals",
        ],
      },
      playerId: "8797",
      playerName: "stewie2k",
      hltvUrl: "https://www.hltv.org/player/8797/stewie2k",
      liquipediaUrl: "https://liquipedia.net/counterstrike/stewie2k",
      highlights: [
        {
          name: "Stewie2k vs. RBG",
          url: "https://hltv.org/news/31346/video-stewie2k-vs-rbg",
        },
        {
          name: "Stewie2K vs. Astralis",
          url: "https://hltv.org/news/27166/video-stewie2k-vs-astralis",
        },
        {
          name: "Stewie2K vs. Liquid",
          url: "https://hltv.org/news/22778/video-stewie2k-vs-liquid",
        },
        {
          name: "Stewie2k vs. NRG",
          url: "https://hltv.org/news/18764/video-stewie2k-vs-nrg",
        },
        {
          name: "Stewie2k vs. Echo Fox",
          url: "https://hltv.org/news/18744/video-stewie2k-vs-echo-fox",
        },
      ],
    },
    {
      playerInfo: {
        name: "EliGE",
        realName: "Jonathan Jablonowski",
        nationality: " United States",
        birthDate: "1997-07-16",
        team: "Team Liquid",
        role: "Rifler",
        approxWinnings: "$989,732",
        age: 24,
      },
      statistics: {
        rating: 1.09,
        adr: 83.7,
        kpr: 0.76,
        dpr: 0.68,
        impact: 1.25,
        totalKills: 28990,
        totalDeaths: 26224,
        mapsPlayed: 1464,
        roundsplayed: 38338,
        hsPercentage: 49,
        kdRatio: 1.11,
      },
      gear: {
        mouse: "Logitech G PRO Wireless",
        keyboard: "Massdrop ALT High-Profile",
        headset: "HyperX Cloud Alpha",
        mousepad: "X-raypad Aqua Control ",
        monitor: "Alienware AW2518HF",
      },
      settings: {
        dpi: 1600,
        sensitivity: 0.74,
        zoomSensitivity: 0.8,
        resolution: "1680x1050",
        scalingMode: "Stretched",
        crosshair:
          "cl_crosshairalpha 255; cl_crosshaircolor 5; cl_crosshaircolor_r 255; cl_crosshaircolor_g 255; cl_crosshaircolor_b 200; cl_crosshairdot 0; cl_crosshairgap 0; cl_crosshairsize 1.5; cl_crosshairstyle 4; cl_crosshairthickness 0; cl_crosshair_outlinethickness 0.5; cl_crosshair_drawoutline 0",
      },
      career: {
        trophies: [
          "ESL Pro League Season 11 North America",
          "IEM Chicago 2019",
          "BLAST Pro Series Los Angeles 2019",
          "ESL One Cologne 2019",
          "ESL Pro League Season 9 Finals",
          "DreamHack Masters Dallas 2019",
          "IEM Sydney 2019",
          "iBUYPOWER Masters 2019",
          "SuperNova CS:GO Malta",
          "cs_summit 2",
        ],
      },
      playerId: "8738",
      playerName: "elige",
      hltvUrl: "https://www.hltv.org/player/8738/elige",
      liquipediaUrl: "https://liquipedia.net/counterstrike/elige",
      highlights: [
        {
          name: "EliGE vs. 100 Thieves",
          url: "https://hltv.org/news/29819/video-elige-vs-100-thieves",
        },
        {
          name: "EliGE - MVP of ESL Pro League Season 11 North America",
          url: "https://hltv.org/news/29494/video-elige-mvp-of-esl-pro-league-season-11-north-america",
        },
        {
          name: "EliGE - MVP of IEM Chicago 2019",
          url: "https://hltv.org/news/27507/video-elige-mvp-of-iem-chicago-2019",
        },
        {
          name: "EliGE - MVP of ESL Pro League Season 9 Finals",
          url: "https://hltv.org/news/27211/video-elige-mvp-of-esl-pro-league-season-9-finals",
        },
        {
          name: "EliGE - MVP of DreamHack Masters Dallas",
          url: "https://hltv.org/news/27071/video-elige-mvp-of-dreamhack-masters-dallas",
        },
        {
          name: "EliGE vs. FURIA",
          url: "https://hltv.org/news/26960/video-elige-vs-furia",
        },
        {
          name: "EliGE vs. MIBR",
          url: "https://hltv.org/news/24346/video-elige-vs-mibr",
        },
        {
          name: "EliGE vs. fnatic",
          url: "https://hltv.org/news/18830/video-elige-vs-fnatic",
        },
        {
          name: "EliGE vs. EnVyUs",
          url: "https://hltv.org/news/18205/video-elige-vs-envyus",
        },
        {
          name: "EliGE vs. fnatic",
          url: "https://hltv.org/news/17442/video-elige-vs-fnatic",
        },
        {
          name: "EliGE vs. YP",
          url: "https://hltv.org/news/17188/video-elige-vs-yp",
        },
        {
          name: "EliGE vs. CSGL",
          url: "https://hltv.org/news/16418/video-elige-vs-csgl",
        },
        {
          name: "EliGE vs. Virtus.pro",
          url: "https://hltv.org/news/16237/video-elige-vs-virtuspro",
        },
      ],
    },
    {
      playerInfo: {
        name: "FalleN",
        realName: "Gabriel Toledo de Alcântara Sguario",
        nationality: " Brazil",
        birthDate: "1991-05-30",
        team: "Team Liquid",
        role: "AWPerRifler (support)",
        approxWinnings: "$1,088,591",
        age: 30,
      },
      statistics: {
        rating: 1.07,
        adr: 72.4,
        kpr: 0.7,
        dpr: 0.6,
        impact: 1.09,
        totalKills: 25916,
        totalDeaths: 22363,
        mapsPlayed: 1418,
        roundsplayed: 37090,
        hsPercentage: 30.8,
        kdRatio: 1.16,
      },
      gear: {
        mouse: "ZOWIE EC1-A",
        keyboard: " ",
        headset: "GFallen Morcego",
        mousepad: " ",
        monitor: "Alienware AW2518HF",
      },
      settings: {
        dpi: 400,
        sensitivity: 2.2,
        zoomSensitivity: 1.2,
        resolution: "1024 x768",
        scalingMode: "Stretched",
        crosshair:
          "cl_crosshairalpha 255 ; cl_crosshaircolor 1; cl_crosshaircolor_r 250; cl_crosshaircolor_g 250; cl_crosshaircolor_b 50; cl_crosshairdot 0; cl_crosshairgap -1.5; cl_crosshairsize 4; cl_crosshairstyle 4; cl_crosshairthickness 1; cl_crosshair_sniper_width 1; cl_crosshair_drawoutline 0",
      },
      career: {
        trophies: [
          "ZOTAC Cup Masters 2018 Grand Finals",
          "ESL Pro League Season 6 Finals",
          "BLAST Pro Series Copenhagen 2017",
          "EPICENTER 2017",
          "ESL One Cologne 2017",
          "ECS Season 3 Finals",
          "DreamHack Open Summer 2017",
          "IEM Sydney 2017",
          "cs_summit Spring 2017",
          "ESL One Cologne 2016",
          "ESL Pro League Season 3 Finals",
          "DreamHack Austin 2016",
          "MLG Columbus 2016",
        ],
      },
      playerId: "2023",
      playerName: "fallen",
      hltvUrl: "https://www.hltv.org/player/2023/fallen",
      liquipediaUrl: "https://liquipedia.net/counterstrike/fallen",
      highlights: [
        {
          name: "FalleN vs. Yeah",
          url: "https://hltv.org/news/29514/video-fallen-vs-yeah",
        },
        {
          name: "FalleN vs. HAVU",
          url: "https://hltv.org/news/29448/video-fallen-vs-havu",
        },
        {
          name: "FalleN vs. ENCE",
          url: "https://hltv.org/news/27876/video-fallen-vs-ence",
        },
        {
          name: "FalleN vs. Liquid",
          url: "https://hltv.org/news/26822/video-fallen-vs-liquid",
        },
        {
          name: "FalleN vs. compLexity",
          url: "https://hltv.org/news/24862/video-fallen-vs-complexity",
        },
        {
          name: "FalleN - MVP of Zotac Cup Masters 2018",
          url: "https://hltv.org/news/24741/video-fallen-mvp-of-zotac-cup-masters-2018",
        },
        {
          name: "FalleN - MVP of BLAST Pro Series Copenhagen",
          url: "https://hltv.org/news/22232/video-fallen-mvp-of-blast-pro-series-copenhagen",
        },
        {
          name: "FalleN - MVP of ESL One Cologne",
          url: "https://hltv.org/news/21030/video-fallen-mvp-of-esl-one-cologne",
        },
        {
          name: "FalleN vs. Astralis",
          url: "https://hltv.org/news/18808/video-fallen-vs-astralis",
        },
        {
          name: "FalleN vs. Natus Vincere",
          url: "https://hltv.org/news/17270/video-fallen-vs-natus-vincere",
        },
        {
          name: "FalleN vs. Na`Vi",
          url: "https://hltv.org/news/16914/video-fallen-vs-navi",
        },
        {
          name: "FalleN vs. Natus Vincere",
          url: "https://hltv.org/news/16620/video-fallen-vs-natus-vincere",
        },
        {
          name: "FalleN vs. EnVyUs",
          url: "https://hltv.org/news/16517/video-fallen-vs-envyus",
        },
        {
          name: "FalleN vs. EnVyUs",
          url: "https://hltv.org/news/15734/video-fallen-vs-envyus",
        },
        {
          name: "FalleN vs. CLG",
          url: "https://hltv.org/news/14469/video-fallen-vs-clg",
        },
        {
          name: "FalleN vs. ProGaming.TD",
          url: "https://hltv.org/news/13226/video-fallen-vs-progamingtd",
        },
      ],
    },
  ];